### ISSUE TITLE
Using collapse's ability causes the game to crash, android 6.0

### ISSUE THREAD

**Issue by Stavinair** [abomb4/dimension-shard#1]
Mindustry has crashed. How unfortunate.
Version: release build 122
OS: Linux x32
Java Version: 0
Java Architecture: null
22 Mods: braindustry:1.4.2, chaos-arranity:2.9.5 Beta, chaotic-creation:2.0, classic-music:2.0, collos:[#EC5EFF]1.2.1[], dimension-shard:0.12, exotic-mod:457 alpha, hackustry:3.3.zip, heavy-armaments:2.2, pixelcraft:0.9.5, prog-mats:0.29, purple-air:0.2.1, ruinous-defense-array:3, substructure:0.1.1, testmod:1.4.7, turretsmod:3, vanilla-upgraded:[white]3.20, diamond-ore:[#9cb6f4]2.3[], emanuel's-mod:0.7 pre alpha, gravillaso: 0.9.3r, improved-gamma:1.1, larger-cores:1.0

> EcmaError: 'ReferenceError: "hit" is not defined. (aat5-collapse#64)'
ScriptRuntime.constructError: 3955
ScriptRuntime.constructError: 3935
ScriptRuntime.notFoundError: 4012
ScriptRuntime.nameOrFunction: 1825
ScriptRuntime.name: 1779
aat5_collapse_66._c_anonymous_6: 64
aat5_collapse_66.call: -1
OptRuntime.callN: 41
skill_framework_63._c_anonymous_39: 439
skill_framework_63.call: -1
ArrowFunction.call: 33
NativeArray.iterativeMethod: 1979
NativeArray.execIdCall: 437
IdFunctionObject.call: 81
OptRuntime.call1: 23
skill_framework_63._c_anonymous_38: 438
skill_framework_63.call: -1
ContextFactory.doTopCall: 346
ScriptRuntime.doTopCall: 3303
skill_framework_63.call: -1
Context.lambda$call$0: 515
-$$Lambda$Context$cFPn5DXqStb0JnJKYei-AlpJVlo.run: -1
Context.call: 524
Context.call: 515
JavaAdapter.callMethod: 549
adapter155.draw: -1
-$$Lambda$ifrumY3k6WQ-gZrF-jKr17eciiM.get: -1
EntityGroup.lambda$draw$0$EntityGroup: 84
-$$Lambda$EntityGroup$7yx2cm6It40ZgVo--jbAiYvhzn8.get: -1
EntityGroup.each: 68
EntityGroup.draw: 81
Renderer.draw: 263
Renderer.update: 94
ApplicationCore.update: 36
ClientLauncher.update: 153
AndroidGraphics.onDrawFrame: 424
GLSurfaceView$GLThread.guardedRun: 1535
GLSurfaceView$GLThread.run: 1240

**Comment by abomb4** [comment]
fixed, but i haven't use pull request, so closed directly
