### ISSUE TITLE
How to get into the new planet?

### ISSUE THREAD

**Issue by SMOLKEYS** [abomb4/dimension-shard#2]
Can i know how to get to the new planet?

**Comment by abomb4** [comment]
1. Finish sector "Plantary Launch Terminal"
2. Build a Interplanetary Accelerator
3. Fill the Interplanetary Accelerator
4. Click the Interplanetary Accelerator
5. Then the new sector at new planet unlocked

**Comment by SMOLKEYS** [comment]
Oh, so its endgame. Ok thanks.
